Vibe-House-LLC/memeSRC

- package-lock.json
- package.json
- src/App.js
- src/components/ipfs/add-cid-popup.js
- src/contexts/V2SearchDetailsProvider.js
- src/contexts/v2-search-context.js
- src/hooks/useSearchDetailsV2.js
- src/pages/ServerPage.js
- src/pages/V2EditorPage.js
- src/pages/V2FramePage.js
- src/pages/V2SearchPage.js
- src/routes.js
- src/sections/search/FullScreenSearch.js
- src/sections/search/ipfs-search-bar.js
- src/sections/server/IndexTable.js
- src/sections/server/ServerInfo.js
- src/utils/jszipObjToImage.js
- src/utils/zipToImage.js
- src/utils/zipsToJszipArray.js
This PR adds a starter "server" page when rendered in Electron. Most of it's still placeholder data, but the ipfs daemon status and toggle controls are working via IPC.
> Add starter server page w/ ipc calls

- src/pages/V2FramePage.js
- src/pages/V2SearchPage.js
- src/sections/server/CidInput.js
- src/sections/server/CreateIndex.js
- src/sections/server/IndexTable.js
- src/sections/server/NetworkGraph.js
- src/sections/server/ServerInfo.js
This PR refactors the server page and connects it to real data via IPC:
**Still needs work:**
- Updating server page components after creating/importing index
- Showing progress bar or some kind of eta when creating new indexes
https://github.com/Vibe-House-LLC/memeSRC/assets/915285/9678e9be-f985-420e-9d0f-3dfcd066f448
> Refactor server page for desktop

- src/sections/server/CreateIndex.js
Quick PR to add a directory selection dialog to the server page when creating a new index.
> Add directory selection dialog

- src/pages/V2EditorPage.js
- src/pages/V2EpisodePage.js
- src/pages/V2FramePage.js
- src/pages/V2SearchPage.js
- src/routes.js
- src/utils/frameHandlerV2.js
- src/utils/videoFrameExtractor.js
This PR formalizes the v2 frame handler and updates the new components to match
> Update to v2 frame handler

- src/pages/V2EditorPage.js
- src/pages/V2FramePage.js
- src/pages/V2SearchPage.js
- src/sections/server/CreateIndex.js
- src/utils/frameHandlerV2.js
- src/utils/videoFrameExtractor.js
This PR includes a slew of bug fixes and performance improvements for the UI's implementation of the V2 data model.
> Fix bugs and improve performance of v2 model

- src/pages/V2EditorPage.js
- src/pages/V2EpisodePage.js
- src/pages/V2FramePage.js
- src/pages/V2SearchPage.js
- src/utils/frameHandlerV2.js
- src/utils/videoFrameExtractor.js
This boosts performance and fixes bugs related to frame extraction. 
The extraction functions now accept an explicit list of frames to extract (instead of ranges), which is a much better fit for our use case and helps reduce unnecessary extractions (or complications to avoid them).
> Improve v2 performance and fix bugs

- amplify/backend/function/memesrcUserFunction/src/index.js
- amplify/backend/package-lock.json
- amplify/team-provider-info.json
- src/App.js
- src/contexts/V2SearchDetailsProvider.js
- src/pages/DynamicRouteHandler.js
- src/pages/HomePage.js
- src/pages/V2EditorPage.js
- src/pages/V2EpisodePage.js
- src/pages/V2FramePage.js
- src/pages/V2SearchPage.js
- src/routes.js
- src/sections/search/FullScreenSearch.js
- src/sections/search/TopBannerSeachRevised.js
- src/sections/search/TopBannerSearch.js
- src/sections/search/ipfs-search-bar.js
- src/utils/fetchShows.js
- src/utils/getV2Metadata.js
This PR sets up the user flow to handle aliases. If there is an alias with the same ID as a v1 metadata object, it will replace it in the shows array. There is a new fetchShows function for v2 that handles checking between aliases and v2 metadata ID's to determine what's being used and return the proper metadata.
> Add alias handling

- src/pages/DynamicRouteHandler.js
- src/pages/HomePage.js
- src/sections/search/FullScreenSearch.js
- src/utils/fetchShows.js
This PR fixes reloading issues with dynamic routes.
> Dynamic route bug fixes

- src/contexts/V2SearchDetailsProvider.js
- src/pages/V2FramePage.js
- src/pages/V2SearchPage.js
- src/routes.js
- src/sections/search/FullScreenSearch.js
- src/sections/search/TopBannerSeachRevised.js
- src/sections/search/TopBannerSearch.js
- src/sections/search/ipfs-search-bar.js
- src/utils/findMidpoint.js
- src/utils/getRandomIndex.js
- src/utils/getSessionsId.js
- src/utils/loadRandomFrame.js
- src/utils/loadV2Csv.js
**Bug fixes and updates include:**
1. Hitting the search page with no search text no longer 404's
2. The random button now works with the new and old data. It also selects a series itself if it is set to universal.
3. Fine tuning on v2 is now locked behind a button. It will wait to load the fine tuning frames until the user chooses to.
4. The search bars everywhere but the home page now have a clear button if there is text.
5. The "IPFS" section of all dropdowns has been removed
6. A bug where the scrolling event listener on the home page was not removed when navigating away from the home page via useNavigate.
> Bug fixes and updates

- amplify/backend/function/memesrcUserFunction/src/index.js
- src/pages/DashboardAliasPageRevised.js
- src/pages/V2EpisodePage.js
- src/pages/V2SearchPage.js
- src/sections/server/IndexTable.js
- src/utils/frameHandlerV2.js
- src/utils/loadV2Csv.js
- src/utils/videoFrameExtractor.js
This PR temporarily removes reliance on an IPFS gateway by using an S3 cache.
> Remove ipfs gateway reliance

- src/pages/V2SearchPage.js
This PR improves `V2SearchPage` with lazy loading and a “load more” button.
> Improve v2 search page

- src/pages/V2SearchPage.js
This PR adds a banner to indicate when you're on a v2 search index.
> Add banner for v2 search indexes

- src/pages/V2SearchPage.js
This PR adds a toggle for animated results to the V2 search results banner. It also adds a way to bring back the banner after dismissing it (to access the setting again).
> Add toggle for animated results

- src/pages/V2SearchPage.js
- src/sections/search/FullScreenSearch.js
- src/utils/fetchShows.js
- Populates index lists with Aliases only.
- Fixes alphabetical sorting on index lists.
- Fixes a permission bug loading indexes.
- Adds a loading indicator when searching v2.
> Fix index lists and add searching indicator

- src/pages/V2SearchPage.js
This PR adds blockers, indications, and helpful functionality for users when Universal Search Maintenance Mode is enabled.
> Implement universal search maintenance mode

- src/sections/search/ipfs-search-bar.js
This PR updates the v2 search component to remove v1 handling like all other search components.
> Fix select series function on v2 search wrapper

- src/pages/V2FramePage-REFACTOR.js
- src/pages/V2FramePage.js
- Fixes v2 frame page throttling to address issues in chrome (**comparison below**) 
- Adds a starting point to refactoring that page with much less code (**currently unused**)
> Fix throttling and begin refactor

- amplify/backend/api/APIGatewayAuthStack.json
- amplify/backend/api/memesrc/schema.graphql
- amplify/backend/function/memesrcSearchV2/src/index.js
- amplify/backend/package-lock.json
- amplify/team-provider-info.json
- src/graphql/mutations.js
- src/graphql/queries.js
- src/graphql/schema.json
- src/graphql/subscriptions.js
- src/layouts/dashboard/header/index.js
- src/layouts/dashboard/nav/config.js
- src/pages/HomePage.js
- src/pages/SearchPage.js
- src/pages/SiteWideMaintenance.js
- src/pages/V2EditorPage.js
- src/pages/V2EpisodePage.js
- src/pages/V2FramePage-REFACTOR.js
- src/pages/V2FramePage.js
- src/pages/V2SearchPage.js
- src/pages/WebsiteSettings.js
- src/routes.js
- src/sections/@dashboard/website-settings/MaintenanceModes.js
- src/sections/search/FullScreenSearch.js
- src/sections/search/TopBannerSeachRevised.js
- src/sections/search/TopBannerSearch.js
- src/sections/search/ipfs-search-bar.js
- src/utils/fetchShows.js
- src/utils/frameHandlerV2.js
- src/utils/loadRandomFrame.js
This PR contains a lot of changes related to migrating the beta to the 'v2 data model' and removing its reliance on v1 systems. 
This version temporarily breaks universal search, but has a "universal search maintenance" setting which can be enabled until the V2 indexes are in opensearch. 
Alternatively, we could continue to use V1 methods temporarily for `_universal` searches. This might be best while indexing to opensearch.
For more info on the changes, check these descriptions:
- https://github.com/Vibe-House-LLC/memeSRC/pull/199
- https://github.com/Vibe-House-LLC/memeSRC/pull/200
- https://github.com/Vibe-House-LLC/memeSRC/pull/202
- https://github.com/Vibe-House-LLC/memeSRC/pull/203
- https://github.com/Vibe-House-LLC/memeSRC/pull/204
- …
> Update beta from dev

- amplify/backend/function/memesrcSearchV2/src/index.js
- amplify/team-provider-info.json
- src/pages/V2SearchPage.js
- src/sections/search/FullScreenSearch.js
- src/sections/search/ipfs-search-bar.js
This PR fixes several bugs with universal search on V2 indexes
> Fix bugs with V2 universal search

- src/sections/search/ipfs-search-bar.js
This PR fixes the back to frame button on the editor page
> Fix back button on editor

- src/pages/V2EditorPage.js
- src/pages/V2FramePage.js
- src/pages/V2SearchPage.js
This PR implements ads into v2 pages
> Implement ads on v2 pages

- amplify/backend/function/memesrcStripeCallback/src/index.js
- amplify/backend/function/memesrcUserFunction/src/index.js
This PR adjusts the backend functions to handle multiple 'price' options, as required by the upcoming Pro plans.
- Only "test mode" prices have been added from Stripe. 
- This will 'break' the purchase flow until being paired with a frontend update.
- The previously enabled discount has been removed.
> Prepare backend functions for pro subs

- src/App.js
- src/contexts/SubscribeDialog.js
- src/contexts/useSubscribeDialog.js
This PR adds a Pro subscription dialog. It still needs to be 'integrated' into the site (it's opening on first load for testing purposes). Slightly related, we should add a premium support form before releasing this (or adjust the referenced perks).
> Add pro sub dialog

- src/pages/V2EpisodePage.js
This PR fixes basic navigation on the episode page and adjusts the design.
> Fix episode page navigation

- src/contexts/V2SearchDetailsProvider.js
- src/pages/V2SearchPage.js
This PR fixes a bug where landing on a page without the search context would cause issues. It also adds in a fail safe if open search is down and will react as if the open search maintenance mode is turned on.
> Beta universal search bug fix

- src/App.js
- src/contexts/SubscribeDialog.js
- src/layouts/dashboard/header/AccountPopover.js
- src/routes.js
- src/sections/search/FullScreenSearch.js
This PR fixes the account popover to show manage account for people with a subscription.
I also updated the subscribe dialog buy button to ask the user to login if they're signed out.
Finally, I added a chip next to the memeSRC title on the home page that says "pro" for users with a subscription.
> Fix account popover

- amplify/backend/api/memesrc/schema.graphql
- amplify/backend/function/memesrcUserFunction/src/index.js
- amplify/team-provider-info.json
- src/graphql/mutations.js
- src/graphql/queries.js
- src/graphql/schema.json
- src/graphql/subscriptions.js
- src/layouts/dashboard/nav/config.js
- src/pages/ProSupport.js
- src/pages/ProSupportAdmin.js
- src/routes.js
This PR adds submission functionality and an admin page for Pro Support messages.
The admin page is ugly, but works for now. lol
> Add pro support submissions and admin page

- src/ads/EditorPageBottomBannerAd.js
- src/ads/EpisodeViewBannerAd.js
- src/ads/FramePageBottomBannerAd.js
- src/ads/MagicToolsLoadingAd.js
- src/ads/SearchPageBannerAd.js
- src/ads/VotingPageFooterAd.js
- src/contexts/SubscribeDialog.js
- src/pages/V2SearchPage.js
This PR adjusts the styling and code layout of the ad containers.
> Adjust ad containers

- amplify/backend/function/AdminQueries9e1cafc6/src/package-lock.json
- amplify/backend/function/AdminQueries9e1cafc6/src/package.json
- package-lock.json
These have been deployed together and [lightly] tested in `dev` without issue:
- https://github.com/Vibe-House-LLC/memeSRC/pull/222
- https://github.com/Vibe-House-LLC/memeSRC/pull/227
- https://github.com/Vibe-House-LLC/memeSRC/pull/228
- https://github.com/Vibe-House-LLC/memeSRC/pull/229
- https://github.com/Vibe-House-LLC/memeSRC/pull/230
> Apply security updates from dependabot

- src/pages/FAQPage.js
- src/routes.js
This PR adds a starter FAQs page design. We should revise the actual content, but this includes a good starting point.
https://github.com/Vibe-House-LLC/memeSRC/assets/915285/802a7588-eca6-42cd-b18f-87d34225e3a6
> Add starter faqs page

- src/App.js
- src/components/v2-feature-section/sections/editor-updates.js
- src/components/v2-feature-section/sections/memesrc-pro.js
- src/components/v2-feature-section/sections/platform-updates.js
- src/components/v2-feature-section/v2-feature-section-popover.js
This PR adds a dialog and sections for the v2 feature list. Once the dialog is dismissed, it will be saved in local storage and will not reappear in that browser.
> Add popover dialog for v2 features list

- src/components/v2-feature-section/sections/editor-updates.js
- src/components/v2-feature-section/sections/memesrc-pro.js
- src/components/v2-feature-section/sections/platform-updates.js
- src/components/v2-feature-section/v2-feature-section-popover.js
- src/sections/search/FullScreenSearch.js
This PR adds a "welcome" page in the v2 updates dialog flow. It also adds the other sections to the home page.
> V2 dialog updates

- src/components/v2-feature-section/v2-feature-section-popover.js
- src/contexts/SubscribeDialog.js
- src/pages/ProSupport.js
- src/pages/VotingPage.js
This PR removes a few hard links to beta.memesrc.com
> Remove beta hard links

- package-lock.json
- package.json
- src/routes.js
This PR fixes the broken donation url by adding a route to handle the redirect to stripe
> Fix donation redirect

- package-lock.json
- package.json
- src/pages/EditorNewProjectPage.js
- src/sections/search/FullScreenSearch.js
This PR updates the total count on the homepage since it doesn't currently update automatically
> Update total count on homepage

- src/pages/V2FramePage.js
- src/utils/frameHandlerV2.js
This PR includes a couple changes:
- New button to clear captions on frame page
- Empty subtitles now return an empty string
> Add clear caption button and fix empty subtitles

- package-lock.json
- package.json
- src/pages/V2EpisodePage.js
This PR increases items per page on the episode page to 250 (matching v1).
> Increase items per page to match v1

- package-lock.json
- package.json
- src/pages/V2EpisodePage.js
- src/pages/V2FramePage.js
- src/pages/V2SearchPage.js
This PR adds a search result count and adjust ad placement / logic
> Display search result count and adjust ads

- amplify/backend/function/frameExtractor/src/index.js
- amplify/team-provider-info.json
- package-lock.json
- package.json
This PR fixes an issue with frame extractions in some cases by adding `-vf "scale=iw*sar:ih"`
> Fix frame extractor scaling

- package-lock.json
- package.json
- src/UserContext.js
- src/components/magic-popup/MagicPopup.js
- src/components/v2-feature-section/v2-feature-section-popover.js
- src/contexts/SubscribeDialog.js
- src/layouts/dashboard/DashboardLayout.js
- src/routes.js
- src/sections/auth/login/GuestAuth.js
This PR changes the "preparing checkout" portion of the buy flow to use a loading button. There is messaging to tell the user that they will be billed by Vibe House LLC through stripe. They are told to check the box beneath the button to proceed to checkout. The checkbox says that they understand that they will be billed by Vibe House LLC through stripe.
This also adds a new /pro path which will load the home page with the subscription dialog open if the user is logged out or not subscribed. If the user is logged in AND has a subscription it will open the magic popover instead.
> Pro messaging updates

- src/contexts/SubscribeDialog.js
This PR adjusts the disclaimer agreement before Pro checkouts. It changes the button to "Agree & Continue" with the disclaimer below and phrasing / links about agreeing to terms & privacy policy.
> Adjust disclaimer agreement

- package-lock.json
- package.json
- src/pages/FavoritesPage.js
- src/routes.js
- src/sections/search/FullScreenSearch.js
- src/sections/search/ipfs-search-bar.js
- src/utils/fetchShows.js
This PR adds functionality and a starter design to the [currently hidden] favorites settings page, which will allow the user to select their favorite indexes. 
In a future release we could add a feature to search 'all favorites' (similar to universal search). 
https://github.com/Vibe-House-LLC/memeSRC/assets/915285/655fef6f-177a-4192-a4f6-976ce19f8616
> Add favorites feature

- amplify/backend/function/memesrcSearchV2/src/index.js
- amplify/team-provider-info.json
This PR adds optimizations for data transfer related to subtitle data:
> Optimize data transfer

- amplify/backend/function/frameExtractor/src/index.js
- amplify/backend/function/memesrcSearchV2/src/index.js
- amplify/backend/function/memesrcUserFunction/src/index.js
- amplify/team-provider-info.json
This PR reduces cost of CloudWatch by removing data-heavy console logs in lambda functions.
> Optimize logs to reduce CloudWatch costs

- package-lock.json
- package.json
- src/components/ImageSkeleton.js
- src/pages/V2SearchPage.js
This PR adds skeletons to search results images while loading.
> Add search result skeletons

- package-lock.json
- package.json
- src/components/magic-popup/MagicPopup.js
- src/layouts/dashboard/header/AccountPopover.js
- src/pages/DashboardAliasPageRevised.js
- src/pages/DynamicRouteHandler.js
- src/pages/HomePage.js
- src/pages/V2EpisodePage.js
- src/pages/V2SearchPage.js
- src/sections/search/FullScreenSearch.js
- src/sections/search/ipfs-search-bar.js
- src/utils/frameHandlerV2.js
- src/utils/loadRandomFrame.js
- src/utils/loadV2Csv.js
This PR adds support for All Favorites searches and random results. It also replaces all instances of img.memesrc.com being used on the front end to an Amplify Storage call.
Finally, this fixes a bug where the last search was not being cleared when going home.
> Add all favorites search

- package-lock.json
- package.json
- src/utils/frameHandlerV2.js
This PR fixes an issue with subtitles not loading in the frame page or editor pages.
> Subtitle hotfix

- src/layouts/dashboard/DashboardLayout.js
- src/layouts/dashboard/header/index.js
This PR adds a memeSRC Pro banner ad
> Add pro banner ad

- src/pages/FacebookAuthDemo.js
- src/routes.js
This PR adds a demo implementation of Facebook authentication
I made a Facebook app for memeSRC with the initial intention to build a poc archival tool to automatically save memes you post to selected groups, but they deprecated the ability to pull groups data literally 3 days ago 👎 but at least we have a starting point for Facebook auth.
> Add demo for Facebook auth

- src/utils/frameHandlerV2.js
This PR fixes a bug where nearby subtitles were empty in cases where the current frame had no matching subtitle.
> Fix bug with nearby subtitles

- amplify/backend/function/S3Trigger016e2873/src/index.js
This PR adds a conditional to ignore src prefix on the s3 trigger function. It also removes console logs from the function.
> Fix s3 trigger prefix

- src/sections/server/CreateIndex.js
This PR updates CreateIndex.js to support fontFamily input.
> Update create index to support font family input

- src/sections/auth/login/CheckAuth.js
- src/sections/auth/login/GuestAuth.js
- src/sections/auth/login/LoginForm.js
This PR reverts recently updated auth functions and pages to a working state
> Revert auth pages and contexts to working state

- package-lock.json
- package.json
- src/pages/V2EpisodePage.js
- src/pages/V2SearchPage.js
- src/utils/frameHandlerV2.js
- Fixes the installation and usage of the `sanitize-html` package to resolve warnings
- Sanitizes html on browse page, which was missing from https://github.com/Vibe-House-LLC/memeSRC/pull/313
> Fix html sanitization

- package-lock.json
- package.json
- src/pages/V2EpisodePage.js
- src/pages/V2SearchPage.js
- src/utils/frameHandlerV2.js
This PR fixes a bug from #314 caused by accidentally decoding from base64 twice.
> Fix subtitle decoding while browsing

- package-lock.json
- package.json
- src/pages/V2FramePage.js
- Sets starting font based on `fontFamily` metadata attribute when available.
- Enables the Akbar font.
> Enable akbar font and use fontFamily from metadata as default

- amplify/backend/function/frameExtractor/src/index.js
- package-lock.json
- package.json
- src/pages/V2SearchPage.js
- Fixes a bug with frame extractions by adding the new `protected` prefix.
- Fixes a bug with the opensearch fallback by using query string params.
> Fix frame extraction prefix and opensearch fallback

- src/pages/V2EditorPage.js
- src/pages/V2FramePage.js
This PR adjust ad placements on the editor pages
> Adjust ad placement

- package-lock.json
- package.json
- src/components/TextEditorControls.js
- src/pages/V2EditorPage.js
This PR adds font settings to text layers on the advanced editor
> Add font settings to advanced editor layers

- src/pages/V2EditorPage.js
- src/routes.js
- Fixes custom image uploads to use V2 editor component.
- Fixes font bugs when removing layers by updating index values.
> Fix bugs when editing custom images

- package-lock.json
- package.json
- src/contexts/useShows.js
- src/sections/search/FullScreenSearch.js
This PR fixes a bug that would cause the shows not to load from the cache under certain circumstances.
It also replaces spot that loads the "default" search from local storage to use an Auth call instead of the user context to get the users sub.
> Fix shows dropdown bug

- src/sections/auth/login/GuestAuth.js
This PR adds an if statement to check if localStorageShows has been set. It also adds conditionals for objects so that they can safely fail without errors if they're undefined or null.
> Guest auth bug fix

- amplify/backend/function/memesrcSearchV2/memesrcSearchV2-cloudformation-template.json
- amplify/backend/function/memesrcSearchV2/src/index.js
- package-lock.json
- package.json
This PR improves search relevance by adjusting the search payload to OpenSearch to boost items that contain an exact match of the query.
> Improve search relevance

- package-lock.json
- package.json
- src/sections/legal/TermsOfService.js
This PR updates the terms of service
> Update Terms of Service

- package-lock.json
- package.json
- src/pages/V2FramePage.js
This PR saves the user's last text formatting settings (unique per index) to localstorage.
> Save format settings per user-index in localstorage

- package-lock.json
- package.json
- src/pages/V2EditorPage.js
- src/pages/V2FramePage.js
- src/sections/search/ipfs-search-bar.js
This PR fixes two bugs:
- When navigating between pages, frames, and subtitles the search term will now stay in the URL
- Switching shows now works as expected in the search bar
> Fix bugs with searching and navigating

- package-lock.json
- package.json
- src/pages/CollagePage.js
- src/pages/V2EditorPage.js
This PR allows editing photos from the collage page by integrating the advanced editor
https://github.com/Vibe-House-LLC/memeSRC/assets/915285/16433be7-2e31-41ab-801d-f1619e2321fd
> Add editor integration to collage page

- src/pages/DynamicRouteHandler.js
- src/sections/auth/login/GuestAuth.js
- src/sections/auth/login/LoginForm.js
- src/sections/search/FavoritesResetDialog.js
- src/sections/search/FullScreenSearch.js
- Adds a dialog to inform relevant users about re-adding their favorites.
- Fixes a bug with blank favorites by changing the default index key.
> Improve transition into reset favorites

- package-lock.json
- package.json
- src/pages/CollagePage.js
This PR adds the ability to multi-select images when creating a collage. It also adds buttons to rearrange the order.
This PR was created with the help of Max Ridgeway.
> Add collage multi-select with rearrange buttons

- package-lock.json
- package.json
- src/components/magic-popup/MagicPopup.js
- src/layouts/dashboard/header/AccountPopover.js
- src/pages/AccountPage-old.js
- src/pages/AccountPage.js
This PR simplifies and integrates the `/account` page showing current subscription details, a manage account button, and a list of invoices. 
This improves previous behavior and fixes bugs where users with `failedPayment` statuses could not access account management.
> Adjust account management page

- package-lock.json
- package.json
- public/index.html
- src/layouts/dashboard/header/AccountPopover.js
- src/pages/AccountPage.js
- src/pages/CollagePage.js
- src/pages/FAQPage.js
- src/routes.js
- src/sections/search/FullScreenSearch.js
- Adds better account management account for various user states
- Update faqs and add standalone linking feature
- Adjust the UI/UX for collage tool interactions
> Improve account page, collage tool, and faqs

- package-lock.json
- package.json
- src/pages/V2EditorPage.js
This PR adds the starting point of a little whitespace feature, currently restricted to dev environments. 
https://github.com/user-attachments/assets/c20a7fec-4d5c-4fce-815c-ad7af321a681
> Add whitespace groundwork to dev

- src/pages/V2EditorPage.js
- src/pages/V2FramePage.js
- Improves the color pallet options for text settings
- Dynamically picks contrasting stroke color
- Adjusts stroke size defaults
> Improve text colors and stroke behavior

- package-lock.json
- package.json
- src/components/TextEditorControls.js
- src/pages/V2EditorPage.js
- src/utils/editorFunctions.js
This PR updates the Advanced Editor with new features and improvements: 
- Adds new 'whitespace' feature
- Adds new text alignment settings
- Adds new text stroke color setting
- Improves font setting display
- Improves font color display
- Displays layer controls by default
> Add whitespace feature and improve text controls editor

- package-lock.json
- package.json
- src/components/FavoriteToggle.js
- src/layouts/dashboard/nav/config.js
- src/pages/FavoritesPage.js
- src/sections/search/FullScreenSearch.js
This PR improves the early-access Favorites Feature: 
- Adds favorite toggle buttons to the homepage
- Adds favorite settings page to the nav bar
- Improves the styling and functionality of the toggles
> Improve favorites feature (early access)

- package-lock.json
- package.json
- src/components/FavoriteToggle.js
- src/pages/FavoritesPage.js
- src/sections/search/FullScreenSearch.js
This PR releases the favorites feature to all authenticated users
> Release favorites feature

- amplify/backend/function/memesrcUserFunction/src/index.js
- amplify/backend/pnpm-lock.yaml
- amplify/team-provider-info.json
- package-lock.json
- package.json
- src/components/CountdownTimer.js
- src/constants/sales.js
- src/contexts/SubscribeDialog.js
- src/layouts/dashboard/header/AccountPopover.js
- src/layouts/dashboard/header/index.js
- src/pages/AccountPage.js
- Improves the account page
- Enhances the pro signup flow
- Adds mechanisms for running sales
- Includes UI for holiday sale
> Improve account features and add sale handling

- package-lock.json
- package.json
- src/layouts/dashboard/nav/config.js
- src/pages/ProSupport.js
- src/sections/search/FullScreenSearch.js
- src/sections/search/TopBannerSeachRevised.js
- src/sections/search/TopBannerSearch.js
- src/sections/search/ipfs-search-bar.js
This PR improves clarity for the anonymous feedback flow via google forms
> Improve feedback flow

- src/contexts/SubscribeDialog.js
This PR improves the behavior of the subscription dialog for memeSRC Pro
> Improve subscription dialog

- src/pages/SubtitleViewerPage.js
- src/routes.js
This PR adds a starting point for a subtitle browser. This could be used for editing, etc.
> Add simple subtitle browser

- src/components/collage/components/CanvasCollagePreview.js
- src/components/collage/hooks/useCollageState.js
- src/components/collage/steps/CollageImagesStep.js
- src/components/floating-action-buttons/FloatingActionButtons.js
- src/pages/CollagePage.js
- src/pages/V2FramePage.js
This PR addresses the following issues:
- https://github.com/Vibe-House-LLC/memeSRC/issues/409
- https://github.com/Vibe-House-LLC/memeSRC/issues/410
- #411 
- #412 
- #413
> Improve collage collector functionality

- src/components/collage/components/CanvasCollagePreview.js
This PR fixes bugs and improves the collage page: 
- Fixes conflicts with page scrolling and image respositioning
- Fixes bugs with undesired button interactions 
- Fixes bugs with the subtitle editor tool tabs
- Improves performance of the collage tool
- Simplifies scroll interaction logic and display
> Improve collage page and fix bugs

- src/components/collage/components/CanvasCollagePreview.js
This PR fixes a bug where non-active collage frames used different styling.
> Fix styling for non-active collage frames

- src/components/collage/components/CanvasCollagePreview.js
Update 'Add Caption' placeholder styling to match default subtitle appearance with reduced opacity.
> Improve caption placeholder style

- src/components/collage/components/CanvasCollagePreview.js
Add dismiss behavior to reposition mode by clicking/tapping outside the active frame or canvas (similar to the subtitle text editor component)
> Add dismiss behavior to reposition mode

- src/components/collage/components/CanvasCollagePreview.js
This PR fixes a bug where text didn't wrap/break in the same way on the exported canvas as it did on the editing canvas.
> Fix text wrapping on export

- package-lock.json
- package.json
- src/pages/V2FramePage.js
This PR hides the 'Add to Collage' button for non-admins as intended
> Fix collage collector visibility

- src/components/collage/components/CanvasCollagePreview.js
This PR consolidates the “Crop & Zoom” and “Reorder” buttons into a single action menu on the collage tool.
> Consolidate collage frame action buttons

- src/components/collage/components/BulkUploadSection.js
- src/components/collage/components/CollageLayoutComponents.js
- src/components/collage/components/MyLibrary.js
- src/components/collage/hooks/useCollageState.js
- src/components/collage/steps/CollageSettingsStep.js
- src/pages/CollagePage.js
- src/pages/V2FramePage.js
Improve functionality of My Library section and adjust the UI
> Improve library behavior and design

- src/components/collage/components/MyLibrary.js
- add local caching for library thumbnails and reduce S3 GETs
- include long-lived cache headers when uploading images
> Improve caching for collage library images

- src/components/collage/components/MyLibrary.js
- Adds a simple 'favorites' feature to the image library, which pins them at the top of the list.
- Improves the UI for image previews when you tap a thumbnail in the library.
The favorites feature only uses local storage to save library favorites, so we'll need to update it to use graphql at some point.
> Add favorites to library and improve ui

- src/components/collage/components/MyLibrary.js
This PR adds the following changes:
- Replaces the delete & create buttons on library multi-select with a continue button that mimics the style of the generate collage button.
> Replace buttons on library multi-select

- v3/package-lock.json
This PR resolves several dependabot alerts by updating `v3` dependencies.
> Update v3 dependencies

- package-lock.json
- package.json
- src/sections/search/FullScreenSearch.js
This PR fixes dynamic homepage colors from affecting the update notice
> Fix colors on update notice

- amplify/backend/function/SearchFunction/src/package-lock.json
- amplify/backend/function/SearchFunction/src/package.json
- amplify/backend/function/memesrcAxiosLayer/lib/nodejs/package-lock.json
- amplify/backend/function/memesrcAxiosLayer/lib/nodejs/package.json
- amplify/backend/function/memesrcFrameFunction/src/package-lock.json
- amplify/backend/function/memesrcFrameFunction/src/package.json
- amplify/backend/function/memesrcOpenAI/src/package-lock.json
- amplify/backend/function/memesrcOpenAI/src/package.json
- amplify/backend/function/memesrcOpenSearch/src/package.json
- amplify/backend/function/memesrcOpenSearchLayer/lib/nodejs/package-lock.json
- amplify/backend/function/memesrcOpenSearchLayer/lib/nodejs/package.json
- amplify/backend/function/memesrcRandom/src/package-lock.json
- amplify/backend/function/memesrcRandom/src/package.json
- amplify/backend/function/memesrcTVDB/src/package-lock.json
- amplify/backend/function/memesrcTVDB/src/package.json
- amplify/backend/function/memesrcc3c71449PostConfirmation/src/package-lock.json
- amplify/backend/function/memesrcc3c71449PostConfirmation/src/package.json
- amplify/backend/function/memesrcinpainter/src/package-lock.json
- amplify/backend/function/memesrcinpainter/src/package.json
- package-lock.json
- package.json
This PR updates axios to `1.12.0` in all `package.json` files that have it listed.
> Update axios version

- amplify/backend/function/memesrcOpenAI/function-parameters.json
- amplify/backend/function/memesrcOpenAI/memesrcOpenAI-cloudformation-template.json
- amplify/backend/function/memesrcOpenAI/src/index.js
Temporarily removes a new secret value related to an upcoming feature
> Remove secret for upcoming feature

- src/components/search/UnifiedSearchBar.tsx
- src/pages/HomePage.js
- src/pages/V2EditorPage.js
- src/pages/V2FramePage.js
- src/pages/V2SearchPage.js
- src/routes.js
- src/sections/search/FullScreenSearch.js
- src/sections/search/ipfs-search-bar.js
- Adds dark mode variant to unified search
- Reuses the unified search on results page
- Removes search input on /frame and /editor
- Improves design and handling of notification
> Improve various designs

- amplify/backend/function/memesrcIndexAndPublish/src/index.js
This PR removes an index if it already exists before reindexing
> Update indexing function to remove index if it exists before reindexing
