src/contexts/V2SearchDetailsProvider.js, src/contexts/v2-search-context.js, src/pages/V2EditorPage.js, src/pages/V2FramePage.js, src/sections/search/ipfs-search-bar.js
This PR uses the new data structure to populate the frame, frame fine tuning, and season/episode/subtitle details on a new V2 frame and V2 editor page.
Still to do: Add nearby subtitle and subtitle navigation (with preview frames as before)
Currently the back and forth arrows look at the current subtitle index and either adds or subtracts 1. I have some minimum logic in to stop it from going to 0, but there will also need to be some logic in place to not exceed the total number of subtitle indexes as well.
=> V2 frame editor pages

src/pages/V2EditorPage.js, src/pages/V2FramePage.js
Small PR to fix the 'direction' of the nav arrows on the frame page, and correct an off-by-one issue in our `fileNumber` calculations.
=> Fix nav arrows and off-by-one miscalculation

amplify/backend/api/APIGatewayAuthStack.json, amplify/backend/api/memesrc/schema.graphql, amplify/backend/function/memesrcUserFunction/src/index.js, amplify/team-provider-info.json, src/components/ipfs/add-cid-popup.js, src/contexts/V2SearchDetailsProvider.js, src/contexts/v2-search-context.js, src/graphql/mutations.js, src/graphql/queries.js, src/graphql/schema.json, src/graphql/subscriptions.js, src/pages/DynamicRouteHandler.js, src/pages/EpisodePage.js, src/pages/HomePage.js, src/pages/V2FramePage.js, src/pages/V2SearchPage.js, src/sections/search/FullScreenSearch.js, src/sections/search/TopBannerSeachRevised.js, src/sections/search/TopBannerSearch.js, src/sections/search/ipfs-search-bar.js
This PR creates a new V2ContentMetadata and Alias type. It also allows linking of metadata to a user.
This also adds two new functions. One function allows a user to submit a CID which will pull its metadata, create it, and link it to that user. It returns the new metadata which the front end will add to their list. If the CID already exists, it will return the existing metadata and attach it to the user as well. The other function is used to pull metadata connected to the user calling the function.
Finally, this also fixes some display bugs on the search, frame, and editor v2 pages. The new frame and editor pages now have display parody of the v1 pages. The v2 search page will now show "no results" when a search has no results.
One last thing to do would be handling errors returned from …
=> Metadata handler

src/components/alias-table-row/AliasTableRow.js, src/layouts/dashboard/nav/config.js, src/pages/DashboardAliasPage.js, src/routes.js, src/sections/@dashboard/alias/alias-management.js, src/sections/search/FullScreenSearch.js, src/utils/fetchShows.js
This PR adds a very basic list to the admin panel that shows the name of shows with their CID's. Next to this is an add button which shows a dialog in which you can type in an alias to assign to the v2 metadata object. If the alias already exists, it will replace it. If it does not exist, it will create it.
This PR also adds some bug fixes to the fetchShows function.
=> Admin alias management

src/pages/DashboardAliasPageRevised.js, src/pages/DashboardCidPage.js, src/routes.js
This PR approaches alias management in a revised way. The new page focuses on C.R.U.D. operations on the **Alias** items themselves (instead of from the index metadata).
=> Add revised alias management page

amplify/backend/api/memesrc/schema.graphql, src/graphql/mutations.js, src/graphql/queries.js, src/graphql/schema.json, src/graphql/subscriptions.js, src/pages/FavoritesPage.js, src/routes.js
This PR includes some groundwork for **Favorites** (i.e. saved indexes):
- Adds `Favorites` type to graphql 
- Add a simple `FavoritesPage` for adding / removing favorites
It utilizes the owner concept for permissions, so we don't need to wrap anything on the backend.
=> Add groundwork for favorites

src/utils/videoFrameExtractor.js
This PR fixes frontend issues with frame extraction by swapping the loadedmetadata event listener with the canplaythrough event listener. It also pauses the video after seeking.
=> Frame extraction bug

src/pages/DashboardAliasPageRevised.js, src/pages/V2FramePage.js
This PR fixes the frame page so that the skeleton shows and the load fine tuning frame button reappears when navigating between frames. This also updates the alias management page to create new V2ContentMetadata objects if they don't exist when adding a cid to an alias.
=> Frame page bug fixes and metadata creation

amplify/backend/function/memesrcSearchV2/src/event.json, amplify/backend/function/memesrcSearchV2/src/index.js, amplify/team-provider-info.json, src/pages/V2SearchPage.js
This PR updates the v2 search endpoint to support multiple indexes (comma separated).
`/v2/search/exampleone,exampletwo,exampleinvalid/test%20search`
Returns: 
```json
{
"results": [
{
"season": "...",
"episode": "...",
"subtitle_index": "...",
"subtitle_text": "...",
"base64_subtitle": "...",
"start_frame": "...",
"end_frame": "...",
"score": 1,
"index_id": "exampleone"
},
{
"season": "...",
"episode": "...",
"subtitle_index": "...",
"subtitle_text": "...",
"base64_subtitle": "...",
"start_frame": "...",
"end_frame": "...",
"score": 1,
"index_id": "exampletwo"
},
{ 
"..." 
},
],
"offline_indexes": [ "exampleinvalid" ]
}
```
The `offline_indexes` key contains an array of indexes which were 'offline' (their docs couldn't be found).
=> Add multi-index support to v2 search endpoint

amplify/backend/api/publicapi/override.ts, amplify/team-provider-info.json, src/pages/V2SearchPage.js, src/utils/videoFrameExtractor.js
This PR isolates the usage of v2 endpoints to their respective environments. Previously, they were all using `dev` endpoint behind a CDN to lean on exploratory changes made in AWS Console. To formalize those settings, these changes were made:
1. Add `override.ts` to handle binary content type setting for each env
1. Add CloudFront distros for each env (`v2-beta` and `v2-dev`)
1. Add Route53 records for the env-specific distros
1. Switch to env-specific cdn urls on the app
**Note:** the CloudFront and Route53 changes are not in the codebase since those are still manually adjusted in the AWS Console directly
=> Isolate v2 endpoint environments

amplify/backend/api/publicapi/override.ts
This PR temporarily removes the binary content type handling to 'hotfix' the app failures due to CORS issues. In other words, this temporarily sacrifices V2 handlers to recover all over API actions in the app. 
**Note:** Since V2 handling is currently down, I've temporarily removed all alias definitions on the beta app to use V1 searches.
The `*/*` binary content type setting in https://github.com/Vibe-House-LLC/memeSRC/pull/196 changes the behavior of the REST API's options requests, which breaks most functionality in the app (due to preflight CORS issues). 
I was using `*/*` because I can't get explicit binary content types to work (i.e. `image/jpeg`, `image/gif`, and `video/mp4`) working due to the "Accept" header handling of this setting on AWS (see "Important" section of [this …
=> Hotfix for API issues

amplify/backend/api/APIGatewayAuthStack.json, amplify/backend/api/memesrcContentApi/cli-inputs.json, amplify/backend/api/memesrcContentApi/override.ts, amplify/backend/api/publicapi/override.ts, amplify/backend/backend-config.json, amplify/backend/types/amplify-dependent-resources-ref.d.ts, amplify/team-provider-info.json
In response to the issues described in https://github.com/Vibe-House-LLC/memeSRC/pull/197, this PR adds and utilizes a standalone REST API specifically for service and searching V2 content. 
In other words, this brings back the V2 content handling which was disabled in hotfix https://github.com/Vibe-House-LLC/memeSRC/pull/197
Not included in this PR is swapping the origins for each env-specific CloudFront distro to utilize the new content api.
=> Add and utilize standalone v2 content api 

src/sections/search/FullScreenSearch.js
This PR switched the homepage index selection to use an MUI `Select` component and populations the options from **Alias** objects in GraphQL.
This isn’t quite production ready:
- Only the homepage uses Aliases 
- Alias permissions incorrectly require auth
=> Change index selection to use aliases and mui

amplify/backend/function/memesrcSearchV2/src/index.js
This PR fixes a bug showing subtitles with special characters by replacing the deprecated `atob` with `Buffer`.
=> Fix special characters in subtitles

amplify/backend/api/memesrc/schema.graphql, amplify/backend/function/memesrcSearchV2/src/index.js, src/graphql/mutations.js, src/graphql/queries.js, src/graphql/schema.json, src/graphql/subscriptions.js, src/pages/SiteWideMaintenance.js, src/pages/WebsiteSettings.js, src/routes.js, src/sections/@dashboard/website-settings/MaintenanceModes.js
This PR adds an admin settings page for setting site wide maintenance mode and universal search maintenance mode.
I've included a wrapper for the site wide maintenance that will still allow us to get to the proper pages to log in and turn it off.
I've also added a comment to the memesrcSearchV2 function so that it will update with the merge.
TODO: I still need to add the popup for the search results page when trying to do a universal search if it is in maintenance mode.
=> Website settings page

src/pages/HomePage.js, src/pages/SearchPage.js, src/pages/V2EditorPage.js, src/pages/V2EpisodePage.js, src/pages/V2FramePage.js, src/pages/V2SearchPage.js, src/routes.js, src/sections/search/FullScreenSearch.js, src/sections/search/TopBannerSeachRevised.js, src/sections/search/TopBannerSearch.js, src/sections/search/ipfs-search-bar.js, src/utils/loadRandomFrame.js
This PR updates routes to remove the /v2/ path and fixes frame and editor page bugs.
Notably, it enforces preloading of fine tuning frames before letting the user slide between them.
I also noticed chrome was still a little iffy when making changes on the current frame page. I found some differences in the code for the refactored page and implemented it on the current frame page. That immediately solved the issues and left them both running equally smooth.
=> Routes and preloading

src/components/nav-section/NavSection.js, src/contexts/SubscribeDialog.js, src/layouts/dashboard/nav/config.js, src/pages/PremiumSupport.js, src/routes.js
This PR adds a **Pro Support** page with a form gated by an active Pro subscription and changes related "Premium Support" phrasing to match. It also adjusts the nav bar icons, order, spacing, etc.
Submissions from the Pro Support page is still placeholder. The form has validation, etc. but it just shows a "TODO" alert instead of submitting it. I figure we can decide what's best and add this functionality in a future PR. 
Unsubscribed vs. subscribed:
The nav bar icons, sizing, spacing, order, etc. has been adjusted.
=> Add pro support page and adjust nav styling

amplify/backend/function/memesrcPublicStripeFunction/src/index.js, amplify/backend/function/memesrcStripeCallback/src/index.js, amplify/backend/function/memesrcUserFunction/src/index.js
This PR updates the 'price' mappings to include the non-test version from Stripe.
=> Add non-test stripe ids for pro subs

amplify/backend/function/memesrcSearchV2/src/index.js, package-lock.json, package.json, src/pages/V2SearchPage.js
This PR improves relevance of search results by: 
- Add scoring for a version of the query with no special characters
- Add another sort condition (prefer shorter subtitles as score tiebreakers)
I noticed the homepage search bar drops special characters (e.g. searching `hello?` leads to a search for `hello`) but I didn't immediately see a fix, so I left it unfixed for now. lol
=> Improve search result relevance

package-lock.json, package.json, src/pages/V2SearchPage.js
This PR temporarily disables the animated thumbnails in search results and hides the 'upgraded index' search banner.
=> Temporarily disable animated results and hide search banner

src/pages/V2FramePage.js
This PR changes the design of elements on the frame page to more closely resemble v1's design. 
It also removes the "Load Fine Tuning" button in lieu of a preload function that happens in the background which immediately makes the fine tuning frames available.
=> Frame page refresh

src/pages/V2EpisodePage.js
This PR improves episode page navigation by: 
- Increase items per page
- 'Skip to start' button
- 'Skip to end' button
We still need to add something that stops items from showing after they've exceeded the highest valid index (which isn't quite trivial since we don't 'know' the last frame, so for now it'd need to rely on broken links or something lol)
=> Improve episode page navigation

src/pages/V2FramePage.js
This PR seemingly fixes a bug on the frame page that would cause the frame/caption to get out of sync when navigating between frames.
=> Fix caption out of sync bug

amplify/backend/backend-config.json, amplify/backend/function/frameExtractor/frameExtractor-cloudformation-template.json, amplify/backend/function/frameExtractor/function-parameters.json, amplify/backend/function/frameExtractor/src/index.js, amplify/backend/function/memesrcSearchV2/function-parameters.json, amplify/backend/function/memesrcSearchV2/memesrcSearchV2-cloudformation-template.json, amplify/backend/function/memesrcSearchV2/src/index.js, amplify/backend/pnpm-lock.yaml, amplify/team-provider-info.json
This PR removes reliance on CloudFront to deliver source data to the frame extractor, which was causing extremely high costs due to outbound data transfer. This change **_intends_** to keep source data transfers as 'internal' to reduce costs. 
These changes require migrating the source data to the amplify-managed bucket in this project. Previously, all environments used the same external bucket behind CloudFront. **This migration is currently in progress and would break images if merged to beta before the migration is complete.**
We need to continue **watching billing console very closely** to catch any other unexpected costs early.
=> Remove reliance on CloudFront for source data transfers 

amplify/backend/function/frameExtractor/frameExtractor-cloudformation-template.json, amplify/backend/function/frameExtractor/src/index.js, amplify/backend/function/memesrcSearchV2/memesrcSearchV2-cloudformation-template.json, amplify/team-provider-info.json, package-lock.json, package.json, src/pages/V2EpisodePage.js
This PR attempts to address lambda costs by:
- Reducing the frame extractor memory.
- Increasing the `max-age` header for caching.
- Showing fewer items per page when browsing.
While I was in there, I also added loading skeletons while browsing.
=> Adjust configs to reduce cost

src/pages/V2EditorPage.js, src/pages/V2FramePage.js
This PR updates the fine tuning section on the frame page and editor page.
On the frame page, the fine tuning frames will not be loaded until the user touches/mouse downs on the slider. The icon changes to a loading spinner while the images are loading.
On the editor, the fine tuning frames preload when the user switches to the fine tuning tab. A linear progress bar will show up under the slider if the images are still loading. If the user has navigated to another frame but still has the slider open, it will wait to load the new fine tuning frame until they interact with the slider.
I also updated the sliders on the frame page to add text to the image on mobile by using the onTouchStart event alongside the mouseDown event.
=> Load fine tuning images upon interaction

package-lock.json, package.json, src/pages/V2EditorPage.js, src/pages/V2FramePage.js, src/routes.js, src/sections/search/ipfs-search-bar.js
This PR fixes a bug on the frame page where selecting a position on the fine tuning slider while the frames were still loading would not update the canvas once the frames have loaded.
It also adds two optional param paths to the editor and frame pages with a fineTuningIndex param. This carries over the selection from both pages, keeping the selected fine tuning frame in sync during navigation.
=> Fix fine tuning

package-lock.json, package.json, src/pages/V2EditorPage.js, src/pages/V2FramePage.js
This PR fixes an issue caused by navigating to the fine tuning frame selection every time the value changes. It now only navigates after the user has finished moving the slider and let go of it via the onChangeCommitted callback of the slider.
=> Frame slider hotfix

src/pages/SourceMediaFileList.js, src/pages/SourceMediaList.js
This PR fixes an issue on the source media page where clicking into an upload would crash/blank out the list. It should now work as intended and load all of the files from the selected upload with the option to download them.
=> Source media page bug fix

src/pages/V2SearchPage.js
This PR fixes the issue where the new result skeletons never stopped showing (was visible behind images that didn't fill the whole result card).
=> Fix skeletons after loading

package-lock.json, package.json, src/pages/VotingPage.js
This PR fixes some console errors on the [voting page](https://memesrc.com/vote): 
- Fixed a null item related error
- Added missing grid item keys
There have been a couple recent reports of the voting page crashing on Android Chrome. This couldn't be reproduced in Desktop Chrome (and I can't test on Android), so I fixed a few console logs to see if it helps.
=> Fix voting page errors

amplify/backend/function/memesrcUserFunction/src/index.js, amplify/team-provider-info.json, package-lock.json, package.json, src/components/magic-popup/MagicPopup.js, src/layouts/dashboard/header/AccountPopover.js, src/layouts/dashboard/nav/config.js, src/pages/InvoicesListPage.js, src/routes.js
This PR adds a new page for subscription management. It shows what plan you're on (using the last paid invoice as reference IF you're still subscribed), and has a button to manage your subscription on stripe. This button works the same way as the manage subscription button in the popover worked.
Additionally, the page also gives you a list of your invoices with a button to download the PDF. It shows the status of each invoice, the invoice number, and the billing period for the invoice. This comes along with a backend function that will return the users invoices.
Finally, this updates all manage subscription buttons to direct the user to this new page.
=> Add subscription management page

src/pages/AccountPage.js, src/routes.js
This PR adds a proof-of-concept Account page (`/account`) based on the [subscription page](https://github.com/Vibe-House-LLC/memeSRC/pull/293) from @AustinWoodard  yesterday. It shifts that idea to be more account-centric to work with any registered user. It also adjusts the subscription and invoices sections and adds _placeholder interfaces_ to update profile picture, email, pass, etc.
This is more a placeholder with partial functionality, so it's currently 'hidden' until we add the rest.
https://github.com/Vibe-House-LLC/memeSRC/assets/915285/0468eae9-abd5-4140-ba9b-6f9b0ae703d1
=> Add account page poc

amplify/backend/function/memesrcSearchV2/src/index.js
This is a hot fix for cases when opensearch is down. The JSON parsing was in a callback, which wasn't being caught with error handling.
=> Add error handling to json parsing

src/pages/FavoritesPage.js, src/utils/fetchShows.js
This PR uses localStorage instead of sessionStorage to cache the index selection dropdown
=> Use local storage for index selection cache

amplify/backend/function/frameExtractor/src/index.js
This PR optimizes the use storage in the Frame Extractor lambda. It wasn't cleaning up temporary files and started failing under load from `no space left`.
=> Optimizing function storage to fix frame extractor

src/utils/frameHandlerV2.js
This PR fixes how metadata is parsed in the fetchFrameInfo function. This also makes the default font functionality that was in place work. I tested this by adding the Akbar fontFamily to Airplane on dev. I've since swapped it back.
I also removed some testing comments in the same function.
=> Fix metadata parsing

src/contexts/useShows.js, src/pages/HomePage.js, src/routes.js, src/sections/search/FullScreenSearch.js, src/sections/search/ipfs-search-bar.js
This PR fixes caching of shows by adding a context that holds the show state. All search pages now look at this context for the show list. It uses a useEffect which will be fired on load and anytime the `user` context changes. 
Most of the logic is directly pulled from the original fetchShows function with some minor tweaks.
=> Fix shows caching

package-lock.json, package.json, src/UserContext.js, src/layouts/dashboard/header/AccountPopover.js, src/pages/HomePage.js, src/routes.js, src/sections/auth/login/GuestAuth.js, src/sections/auth/login/LoginForm.js, src/sections/search/FullScreenSearch.js, src/sections/search/ipfs-search-bar.js, src/utils/fetchShowsRevised.js
This PR does a few things:
- Shows are now handled inside the guest auth wrapper
- The default show is handled by the guest auth wrapper
- There is a new fetchShowsRevised function that is used to return shows
- Shows and the default show are both cached under separate keys in local storage, but everything is handled exactly as the user details.
=> Add shows handling to guest auth wrapper

amplify/backend/function/frameExtractor/frameExtractor-cloudformation-template.json, amplify/backend/function/frameExtractor/function-parameters.json, amplify/backend/function/frameExtractor/src/index.js, amplify/backend/pnpm-lock.yaml, amplify/team-provider-info.json
This PR updates the frame extractor lambda to use s3 as a 'long term cache' for extracted images.
=> Save and reuse extracted image data

package-lock.json, package.json, src/pages/V2EditorPage.js, src/pages/V2FramePage.js, src/pages/V2SearchPage.js
This PR rounds frame numbers to the nearest equivalent whole-second timecode in:
- **Search Results** (images and frame page links, which intrinsically rounds nearby frames)
- **View Episode Links** (the bottom buttons, and frame page timecode & episode number buttons)
This should normalize all 'starting points' and improve cache hit rates by almost 10x (the current 'fps' value). 
Previously, searches results would provide the 'middle' frame of the matching subtitle range. This works fine, but since the nearby frames and episode browsers simple do whole-second steps to find other frames, it decreases likelihood of cache hits by a factor of 10 (the current 'fps' value).
=> Improve cache hit rate by rounding frame selections

package-lock.json, package.json, src/components/nav-section/NavSection.js, src/layouts/dashboard/nav/config.js, src/pages/EditorNewProjectPage.js, src/sections/search/FullScreenSearch.js
This PR improves the 'discoverability' of the collage tool in early access: 
- Adds and utilizes a new option to show chips on nav bar items (shows "Pro" beside it).
- Adds a homepage 'alert' component account it.
- Adds a 'tools' page section to launch it.
In the future, we could also integrate it as a step in the normal edit flow.
=> Improve discoverability of collage tool

package-lock.json, package.json, src/contexts/SubscribeDialog.js, src/sections/legal/TermsOfService.js
This PR unblocks Canada from subscription safeguards. It also updates the terms of service to include Canada when referencing countries.
=> Unblock canada

src/pages/DynamicRouteHandler.js
This PR improves a couple behaviors of the dynamic routes handler: 
- Routes to `/_universal` will now update the default and forward to `/`
- Invalid routes now show the 404 page without changing the path to `/404`
=> Improve dynamic route handling

amplify/backend/function/frameExtractor/src/index.js
This PR attempts to start debugging an issue related to loading frames. I added some extra logging and removed a redundant call to S3. I doubt that will fix anything, but the logs should help us start to debug. 
We noticed some cases where the image extractor flow fails to initially load some images (with a `502` error). This tends to be more likely if you're opening a page which contains many images, which would all try to load at once.
=> Add logging and remove redundant S3 request

src/pages/CollagePage.js
This PR fixes the canvas size limit issue in the collage tool by resizing images before drawing them on the canvas.
=> Fix collage bug with large images

src/components/collage/components/CanvasCollagePreview.js
Fixes issue #415: 
- https://github.com/Vibe-House-LLC/memeSRC/issues/415
**What changed:**
- Collage now zooms from cursor/pinch point instead of image center
- Updated `CanvasCollagePreview.js` zoom behavior for both mouse wheel and touch gestures
**Implementation details:**
- Modified `handleWheel` to calculate cursor position relative to canvas/panel
- Updated `handleTouchMove` to use pinch gesture center point via `getTouchCenter`
- Added proper bounds checking to prevent whitespace after zoom-from-point calculation
- Fixed ESLint `one-var` rule violations by splitting variable declarations
**Result:** Users now get the expected zoom behavior where the point under their cursor/finger stays stationary during zoom.
=> Resolve collage zooming issue

src/components/collage/components/CanvasCollagePreview.js
**TL;DR – this PR fixes Mobile but does not fix Desktop**
The description below was written by Cursor based on the initial request. After a couple attempts, it has fixed the issues on Mobile but still has issues on Desktop. I say we go ahead and consider this a fix for Mobile only, and open a separate PR to fix Desktop behavior.
Scrolling behavior in the collage tool was refined to prevent unintended page scrolling during image manipulation.
Previously, page scrolling was globally disabled when any collage panel was in transform mode, affecting both desktop and mobile interactions.
Changes were applied to `src/components/collage/components/CanvasCollagePreview.js`:
*   **Desktop (`handleWheel`):** The `e.preventDefault()` call was moved to occur only when the mouse wheel event is actively …
=> Fix behavior while repositioning collage image on mobile

src/components/collage/components/CanvasCollagePreview.js
Implement click-outside-to-dismiss for the subtitle editor settings panel. This allows users to close the editor by clicking outside its boundary, mimicking the 'Done' button's behavior for improved usability.
=> Add dismiss behavior for subtitle settings

src/components/collage/components/CanvasCollagePreview.js
This PR fixes a bug while rearranging collage frames, specifically when one frame has a caption and the other doesn't.
To test these changes, I recommend:
1. Create a 2+ frame collage
2. Add a caption to one frame
3. Leave another frame blank 
4. Rearrange the frames a few times
If it's working correctly, the caption and empty will remain attached to their respective images while rearranging.
=> Fix caption swap when rearranging panels

src/components/collage/components/BulkUploadSection.js, src/components/collage/components/CollagePreview.js, src/pages/V2FramePage.js
The PR includes the following fixes:
-Clicking empty frame on collage editor, it allowed you to select multiple to upload. It now only allows a single photo to upload.
-When we used the save to library button on the frame page, it engrained the subtitles into the imported image to library. It now uses the original image without engrained subtitles regardless if the frame page preview image is displaying subtitles or not.
=> Bug fixes for library

amplify/backend/function/memesrcAggregateVotes/src/package.json, amplify/backend/function/memesrcIndexToOpenSearch/src/package.json, amplify/backend/function/memesrcOpenSearch/src/package.json, amplify/backend/function/memesrcPublicStripeFunction/src/package.json
This PR adds the `aws-sdk` package to the `package.json` files for lambda functions that use it
=> Add aws-sdk packages to lambda functions that use it

src/components/collage/components/BulkUploadSection.js, src/components/collage/components/EarlyAccessFeedback.js, src/pages/CollagePage.js
This PR simplifies the content on the collage page:
- Hides the beta controls card
- Clarifies the instructions
- Simplifies the title
=> Simplify collage page content

package-lock.json, package.json, src/sections/@dashboard/user/user-list.js
This PR fixes a bug when loading all users via the search by adding optional chaining to the values in the filter.
=> Add optional chaining to filtered users

src/sections/@dashboard/admin/uploads/review-upload.tsx
This PR fixes a bug that allowed users to start an extraction without an alias.
It also fixes a bug where the file browser would reload anytime a file status changed. Now it only reloads when a files status changes to "extracted" specifically, and only attempts to load if at least one file is extracted.
=> Disable extraction without alias
